apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - name: vault
      port: 8200
  selector:
    app: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  conf.hcl: |-
    listener "tcp" {
        address = "0.0.0.0:8200"
        tls_cert_file = "/vault/config/cert.pem"
        tls_key_file = "/vault/config/cert.key"
    }

    backend "inmem" {
    }

  cert.pem: |-
    -----BEGIN CERTIFICATE-----
    MIID2DCCAsACCQDx6eKn6Yy4fDANBgkqhkiG9w0BAQUFADCBrDELMAkGA1UEBhMC
    VVMxCzAJBgNVBAgMAlZBMRAwDgYDVQQHDAdIYW5vdmVyMSowKAYDVQQKDCFLYWlu
    b3MgSGVhbHRoY2FyZSBTb2x1dGlvbnMsIExMQy4xFDASBgNVBAsMC0RldmVsb3Bt
    ZW50MQ4wDAYDVQQDDAV2YXVsdDEsMCoGCSqGSIb3DQEJARYdbXdvb2RhcmRAa2Fp
    bm9zaGVhbHRoY2FyZS5jb20wIBcNMTcxMTA5MDAwNzUxWhgPMjA4NTExMjYwMDA3
    NTFaMIGsMQswCQYDVQQGEwJVUzELMAkGA1UECAwCVkExEDAOBgNVBAcMB0hhbm92
    ZXIxKjAoBgNVBAoMIUthaW5vcyBIZWFsdGhjYXJlIFNvbHV0aW9ucywgTExDLjEU
    MBIGA1UECwwLRGV2ZWxvcG1lbnQxDjAMBgNVBAMMBXZhdWx0MSwwKgYJKoZIhvcN
    AQkBFh1td29vZGFyZEBrYWlub3NoZWFsdGhjYXJlLmNvbTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAMgSUFbykCsXiE/ufdwHJfVhxpxJQLGTxSldlO5B
    pQgl4/KVA6dCNlANSjqhUaWDbAQXc3qZosZQtiLJaTMKxhqRB/ysZHvjnY7SNuym
    0CAA6TXidNchOWfRfvz3I0f4OAxVc9sG43B0KGfb8PT1JghYCTnNOCFQej6SbVjM
    SqWmULXP6QWQMMyFNPW7egawX/wIQVkZQmSiQjN/FazOFmVLnJGPPWEcSpRBomWt
    EHNRcZ4SA9e54A5gNaVdRmTRjiF0olWB5lZ7d5x8eO4KT+F48RuDgQ7c5vGdHr8f
    jGSu0k/5NddQ4Xv5PQyfZvHTEqhB2iDFE7ahjh5vdaxwMqkCAwEAATANBgkqhkiG
    9w0BAQUFAAOCAQEAIwMgCI5Riwfjpv/Y4ewHLApr4SqrVf9H2TYLevDNZqLB3hGV
    WLNxZ23i8aOapgi4pxf8BTQE55KBxwR6gqSDryEGFGsKr/RqCSnj4gTzCs0CS/8D
    ZzPY6tc9VPhkUFgU1FJXw0cycNXRLA2NhTamEXbfZXOQFdqsz8FnJUz49ka4ppW3
    a2klJthwpMQlnyjZwMX/E5EEbZvMX2TRMjxHlVuIq/ZwNs/rJjN/6vjVNYkt/Gc6
    jcuiDxYAwXKwXeTOVugje38kcQJNHEBHjHdWZJj6vKi4YzJgbqDyr858nI1pfyWI
    JU10tu4pypYXf1qtVItsbmgYwEIEGKdlkauQYg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIID7DCCAtQCCQDQ2ciWCappRTANBgkqhkiG9w0BAQsFADCBtjELMAkGA1UEBhMC
    VVMxCzAJBgNVBAgMAlZBMRAwDgYDVQQHDAdIYW5vdmVyMSowKAYDVQQKDCFLYWlu
    b3MgSGVhbHRoY2FyZSBTb2x1dGlvbnMsIExMQy4xFDASBgNVBAsMC0RldmVsb3Bt
    ZW50MRgwFgYDVQQDDA9LSFMgRGV2ZWxvcG1lbnQxLDAqBgkqhkiG9w0BCQEWHW13
    b29kYXJkQGthaW5vc2hlYWx0aGNhcmUuY29tMCAXDTE3MTEwOTAwNDEzM1oYDzIw
    ODUxMTI2MDA0MTMzWjCBtjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMRAwDgYD
    VQQHDAdIYW5vdmVyMSowKAYDVQQKDCFLYWlub3MgSGVhbHRoY2FyZSBTb2x1dGlv
    bnMsIExMQy4xFDASBgNVBAsMC0RldmVsb3BtZW50MRgwFgYDVQQDDA9LSFMgRGV2
    ZWxvcG1lbnQxLDAqBgkqhkiG9w0BCQEWHW13b29kYXJkQGthaW5vc2hlYWx0aGNh
    cmUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyBJQVvKQKxeI
    T+593Acl9WHGnElAsZPFKV2U7kGlCCXj8pUDp0I2UA1KOqFRpYNsBBdzepmixlC2
    IslpMwrGGpEH/Kxke+OdjtI27KbQIADpNeJ01yE5Z9F+/PcjR/g4DFVz2wbjcHQo
    Z9vw9PUmCFgJOc04IVB6PpJtWMxKpaZQtc/pBZAwzIU09bt6BrBf/AhBWRlCZKJC
    M38VrM4WZUuckY89YRxKlEGiZa0Qc1FxnhID17ngDmA1pV1GZNGOIXSiVYHmVnt3
    nHx47gpP4XjxG4OBDtzm8Z0evx+MZK7ST/k111Dhe/k9DJ9m8dMSqEHaIMUTtqGO
    Hm91rHAyqQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQC+tUF2fcNrNkY0M5A9rrry
    6x21NYNZMgw8i08fY2rLKBmdQkghHpgcEKsXQWP7NsahgF2Mv3yqNwwXOpdBbx1N
    kvmkUsK302LvCWL4aynuMtvlFxHALXOE0eSznLc4iarCIh5iO2BuOcpu0o6USfpn
    aRfHXLHRyEAFzHnkTNmBrZ9IV2es83TMkaUQVMKpN7dmET/tWsFdoeS5VmJxXo99
    8RK20e+IHuzQZMLmhjTNSSmaBbL76ep5suENmJ4Rq+UPUGlZYwql11ugnSK9E35H
    v5mli5MGBELja0era8x94PoG5pAvpi6s56W5PKRqNKw9kw2ck8BFUMGyoSO+iWLp
    -----END CERTIFICATE-----

  cert.key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAyBJQVvKQKxeIT+593Acl9WHGnElAsZPFKV2U7kGlCCXj8pUD
    p0I2UA1KOqFRpYNsBBdzepmixlC2IslpMwrGGpEH/Kxke+OdjtI27KbQIADpNeJ0
    1yE5Z9F+/PcjR/g4DFVz2wbjcHQoZ9vw9PUmCFgJOc04IVB6PpJtWMxKpaZQtc/p
    BZAwzIU09bt6BrBf/AhBWRlCZKJCM38VrM4WZUuckY89YRxKlEGiZa0Qc1FxnhID
    17ngDmA1pV1GZNGOIXSiVYHmVnt3nHx47gpP4XjxG4OBDtzm8Z0evx+MZK7ST/k1
    11Dhe/k9DJ9m8dMSqEHaIMUTtqGOHm91rHAyqQIDAQABAoIBAQC2jr9wFvUl3Nss
    1FlTo9InDYjEorK9VjDZheKXZJ7JyIkumHo07F3Svc21oe12MW0mbp+YhwfYHV2U
    cGPlhzcslpnLHSKzSQZDg91KIwxVp38lA/XJNy/CY46UFI3E5eF+n5qPiMGPou4b
    lr1PR0Hk6y+/5loJS/2/iqzsEb0rV/CGHTd/iJostK8BewR0vvLMPAbsTQNSJIfU
    ZZX6BU7K+tLKSEXXfh5XcancxXPAOSndHMNlg7cFeH4LLyVCBi9ybW3VyDy/4wUG
    YmJtE5+0G44TL5L5CYPZmANK6aiHj4t6X2RS7CeLxHIybJ55Vy4MGmMr0YYMZZFJ
    qdI9Ie2BAoGBAPU0sduxed4gmF5fFQ39EbTK0ol2fbjWqm8rIeiv7L+FHLCB4OGU
    +6un8EBNFjPWmOp0UD65NkUQymAz9nM1oJplTIzhN3ZE8zDC/444RjNlKcW/JYoY
    MaEsnex1giGQD9aC41USpw9yhrXNlfOIwbKo7U5RlBsWx4v5C9oRKxW9AoGBANDg
    /FzddBXTR8iflHw0EnYhFZSkoxLJskJeByuNFRV2NvIRI/+JH1QjFGIAAKZoinTH
    k0J9UKAw7KLX/CRhUJcpUROxouNhFxodx6z2z3YCehs8UktQAGQQs5dfpiuAcLyJ
    rJKSP77TC5bMp8Xr3nxf30Bnb3/GH/Og30sG0tFdAoGBAN+wRJiQXQaAYb+lqcVr
    Gh398Pap+6MFYdGsXXCyHJ3SxwtWUFo52SUNPSTLrfd4S2OG3DV8LL/ww03j2W3c
    fDidNKpIQppH6DqRiSSqvY/hN6xH5e0GiS/pTeAKir4nd+tO2Cghrflvluh/Nc5G
    8b0UUffif+P+ceeFOISkqNNZAoGBAIxpYVuvxjRRteSIWZFwk6RzMwWb8r9TdJAm
    kx1UloK518+7c/54F+ZAOphyNf2nMsOz0SsWAFfe64PAOw/dlwY2UPkzJTNCdfwp
    XqvHscg7fAfI8e0Ml2asz30HYDXH/oDO74IL6+wEBLtXUcS7fPEQpYuuvIYhEiN8
    1f2iVZ9FAoGAaPIhb/j1rq3P+0TXajsJ2OeXuVSbJSLsfuQKawvIEmpCgQ0ZTPPQ
    9QCsnZG0K9cwhqBH63/n+IOMTqYT4khKEbdweHAWhoKdT1Jac9mFK1rW3ItkFcJ2
    r9w71angiyjj/EzQcdEEycgghxOgLO+N2R+QEtsYc7UEEvBvStZywFI=
    -----END RSA PRIVATE KEY-----
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        command:
          - vault
          - server
          - -config=/vault/config/
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /vault/config
        securityContext:
         capabilities:
           add:
             - IPC_LOCK
      volumes:
        - name: config-volume
          configMap:
            name: vault