apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - name: vault
      port: 8200
  selector:
    app: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  conf.hcl: |-
    listener "tcp" {
        address = "0.0.0.0:8200"
        tls_cert_file = "/vault/config/cert.pem"
        tls_key_file = "/vault/config/cert.key"
    }

    storage "zookeeper" {
      address = "zk-cs.default.svc.cluster.local:2181"
      path    = "vault/"
      advertise_addr = "https://vault:8200"
    }

  cert.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIELDCCAxSgAwIBAgIRAIXdOZxVSzt1kfyWlYaAAlYwDQYJKoZIhvcNAQELBQAw
    FjEUMBIGA1UEAwwLRWFzeS1SU0EgQ0EwHhcNMjEwNTE0MTgwOTEzWhcNMjQwNDI4
    MTgwOTEzWjAXMRUwEwYDVQQDDAx2YXVsdC1zZXJ2ZXIwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQCStWwMMmTSalORWeIGqtrrNLIEbZdyxhnW8Yg0cn5B
    uR7JuF8+/LogePsMzxwXrrzAV9eaDOA6he23eIDX3IFM6OoLTOR3KLW6/HFeJtyL
    QDQY4dDMQz4CHBeoAXRfv67YSWCT/f+cbiEw9a1aK/pnQYEwJfrCJtYjDnZ5/1WU
    UyWYR+gYiqb+ShVHDHjtb10jm5foQ2iFT5GBPNvUR1rTdwx/frdSR66zKQGZd3ab
    GD+dxQ3hYPLW4DQoIIiZAzR/B4OfD+L8rRvRYFdgATedhrDOHkCz444kWph/75eT
    I5RGdcE8rzBjtu+Jnbg/sCJadjnK9uy4IkOUMbi3oUt3AgMBAAGjggFyMIIBbjAJ
    BgNVHRMEAjAAMB0GA1UdDgQWBBQaPzsVPbr0bpmKF54sK8SgxkeTPjBGBgNVHSME
    PzA9gBRs72VPDZ8t56vwshqD5EFIvzuI2KEapBgwFjEUMBIGA1UEAwwLRWFzeS1S
    U0EgQ0GCCQDA1bDVjmvupzATBgNVHSUEDDAKBggrBgEFBQcDATALBgNVHQ8EBAMC
    BaAwgdcGA1UdEQSBzzCBzIIHKi52YXVsdIIPKi52YXVsdC5kZWZhdWx0ghMqLnZh
    dWx0LmRlZmF1bHQuc3ZjgiEqLnZhdWx0LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9j
    YWyCDHZhdWx0LWFjdGl2ZYIUdmF1bHQtYWN0aXZlLmRlZmF1bHSCGHZhdWx0LWFj
    dGl2ZS5kZWZhdWx0LnN2Y4IoKi52YXVsdC1hY3RpdmUuZGVmYXVsdC5zdmMuY2x1
    c3Rlci5sb2NhbIIFdmF1bHSCCWxvY2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEA
    D4yAxWoOa0eh3ljaWGtzZhsQ8ROctrb+O+SWcPyiKLkK3g4Kn7vp/2Acq5gU3H6y
    BpsZX/l2i1/XOejc7eQw5Ip5D+2lOuifcf4Bxt+DLrD3LiWe9UIe2OzLc06ik8Xx
    6wmNXO3CQog5fDzriatl3d94uzEb+CH18YTBF3wtAqmG7wQTXFEoW8HCk+b83qoe
    5o3eoVP0hs+Nai4gnO+Y746RCmwod7+Oqkd+ReMDUSB18wG/vwG6pAaTDeTPuFwR
    tDE0QSfrf8cGjeomp9gVRT7tOs1fWtfCIKuj7vC4DcMoptsz2SeYRoLcMAcdWvi8
    GFdwLve9vTjxHeuTGhtQMg==
    -----END CERTIFICATE-----

  cert.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCStWwMMmTSalOR
    WeIGqtrrNLIEbZdyxhnW8Yg0cn5BuR7JuF8+/LogePsMzxwXrrzAV9eaDOA6he23
    eIDX3IFM6OoLTOR3KLW6/HFeJtyLQDQY4dDMQz4CHBeoAXRfv67YSWCT/f+cbiEw
    9a1aK/pnQYEwJfrCJtYjDnZ5/1WUUyWYR+gYiqb+ShVHDHjtb10jm5foQ2iFT5GB
    PNvUR1rTdwx/frdSR66zKQGZd3abGD+dxQ3hYPLW4DQoIIiZAzR/B4OfD+L8rRvR
    YFdgATedhrDOHkCz444kWph/75eTI5RGdcE8rzBjtu+Jnbg/sCJadjnK9uy4IkOU
    Mbi3oUt3AgMBAAECggEATX6blk3ASA12Gx85b4Asp3VsWz5wc2YFHC71XY7k9l6M
    zs0fMqxYvPJq2jdEhZX9ijRcZLlMcF1yVinHFT8a5b9acaGqRO8yH5VdZPhuIvhF
    DKernVoflQm1zT8Hc9RSzVjlNQdEUCM0USJU8X6thIFrdj15mbjeACKRnpurXu9H
    /WYpOKTu3lTZdcckFgRSwq+0QMZU3MJ31HHHp9NbIgZRoviJzTVvaJibIt9kCvVs
    qE/El8uTuGlR3Wz+S+eToCJuoP1LdAKwyKagxMLqcOmaCiJNrJrVbmfDHp747OUZ
    zqIxEJ++78K49tgxhWaiYT6zqJqcHuEV8LlJCoCzYQKBgQDCBpVVaX1BJc8Wcwph
    10xgdMqNFMb1HStinmRgfltJ+ayNJwL3L6tIx9eipjjXU+N+SJnxwCC+lENmNoRM
    HdwqxiF8TT8rvq/uCkMsKqnv+tiZwUjRG5Tf6hiHZlF3R+izlaAIyDWfAwaYcK/q
    2Rux6PKWz01CgB6+50QCx1DvvwKBgQDBkb2lZufVuPrXd6Pkyrv4D5lOgGgLFbyH
    z8T5GQ3HqN6ooTgjxvpPXT68y+oEQvrmS3pRgpywhpv1muPlVO+jXOO7AeuZyR4N
    FPzTzdP+tRBNqCBKHEKJqFTHl0meliuyrlmifF3iXxB/2NXXAJ3RVWPzJmOZb5m0
    X+hye66SSQKBgE2PgCaykqV2TcA1oJLYE+oDBe07vwTA8lTr6EhCeo+pxPZv/9l8
    LsZbTLHyLIq3OBuFPjTLjstgTUkQxfX/gcF/jmc4IeaExaMsawm+zEvoRKnCAC/H
    DM4tsDyABFTgY/9V8rFQB09XUE2jzk7dFxsZedAbclEBEklR/Xf24T3VAoGACrHn
    vYzLAGcBDQiiOJDvA8yw1sKHfR1NVl+nbW/x7/cnnj+SH3/t8pafUcUef+/HdxPy
    hTBnQeWeFlrhfplLyEXomzuG7e9LxsNDGNzFesw8Q14nspCPKJXxYTm9qpJ3hZ7W
    ewDOGyTPf5DWd9Oj5J4IMLYNSLv+zRWDfVfSFGkCgYEAtTwDa7WwOaL3OApXPZdi
    ahGgP6fDf0JAX7V++w0UwYwyzFRU0kT4Rs2s0tMg/9E63CZJKzVMmm5ZLEA18Gi/
    Mgp8awQ78DZm4X2wvXBZ/slk1FCekgcCgfmVNubt3PXVJEwRDQCMrYMf88cvrZ7j
    T041yyFtJHqzO7b0hM3ej28=
    -----END PRIVATE KEY-----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        command:
          - vault
          - server
          - -config=/vault/config/
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /vault/config
        securityContext:
         capabilities:
           add:
             - IPC_LOCK
      volumes:
        - name: config-volume
          configMap:
            name: vault
